### ISSUE TITLE
pre-trained models?

### ISSUE THREAD

**Issue by zemanet2020** [cisert/rescoss_logp_ml#1]
Where are the pre-trained models? Can we download them?

**Comment by cisert** [comment]
When you complete the setup (see readme), it will automatically download those models. The download happens in https://github.com/cisert/rescoss_logp_ml/blob/6384d6e223dc9159761a1b4cf3441b85f5afe4cb/rescoss_logp_ml/data_handling/download.py#L16 
Let me know if this doesn’t work
